name: Workflow

on:
  push:
    branches:
      - main

env:
  GCP_REGION: us-central1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run tests
        run: poetry run pytest tests/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: build and push the docker image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/images/crawler_api:latest .
          docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/images/crawler_api:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4

      - name: Deploy Cloud Run service with Terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="cloud_run_image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/images/crawler_api:latest" \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION }}" \
