name: Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run tests
        run: poetry run pytest tests/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawler-api-image:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawler-api-image:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4

      - name: Deploy Cloud Run service with Terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="cloud_run_image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/crawler-api-image:${{ github.sha }}" \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION }}" \
