name: Workflow

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: criscon
  REPOSITORY: images
  SERVICE: crawler-api
  REGION: us-central1
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run tests
        run: poetry run pytest tests/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Create Service declearation   
        run: |
          export IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          export SERVICE="${{ env.SERVICE }}"
          envsubst < ./service.template.yaml > service.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          flags: '--platform=managed --allow-unauthenticated'
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          metadata: service.yaml
